---
- name: Install ArgoCD using kubectl
  shell: |
    kubectl create namespace argocd
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  args:
    creates: /etc/kubernetes/manifests/argo-cd
