apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: giropops
  project: cflblabs
  source:
    path: samples/descomplicando-argocd/giropops-senhas/helm
    repoURL: https://github.com/cflb/argolab.git
    targetRevision: develop
  syncPolicy:
    automated: {}